### ISSUE TITLE
UI Breaks on Higher Res

### ISSUE THREAD

**Issue by SyndicateRP** [iONDegen/ps-inventory#12]
So on 1080p it works perfect. When you go up to 1440p and 4k is breaks the UI.
![image](https://github.com/iONDegen/ps-inventory/assets/140398712/5ec691fc-e3c4-41a1-8476-6cac6adea8aa)
Here is an example of 1440p
![image](https://github.com/iONDegen/ps-inventory/assets/140398712/1d6698a5-db16-4330-8602-c27c8eff93f4)
and here is 1080p

any help is appreciated!

**Comment by SyndicateRP** [comment]
Fixed this. Did some research on stackoverflow and MDN and edited the CSS myself. Appreciate the awesome UI! If anyone else needs this code for 1440p compatibility just let me know :D

**Comment by ScrewWorldRP** [comment]
@SyndicateRP can you please send the code? I'm have the same issue.

**Comment by neilouo0921** [comment]
I want to support 1440p

**Comment by Cyni4l** [comment]
> Fixed this. Did some research on stackoverflow and MDN and edited the CSS myself. Appreciate the awesome UI! If anyone else needs this code for 1440p compatibility just let me know :D

Hi SyndicateRP - would you mind sharing the changes you made with me as well?

**Comment by Brave-developments** [comment]
> > Fixed this. Did some research on stackoverflow and MDN and edited the CSS myself. Appreciate the awesome UI! If anyone else needs this code for 1440p compatibility just let me know :D
> 
> Hi SyndicateRP - would you mind sharing the changes you made with me as well?

https://youtu.be/WK93Ew5fMwI
