### ISSUE TITLE
When Robbing people just normal inventory shows up

### ISSUE THREAD

**Issue by themysticg** [iONDegen/ps-inventory#16]
Please tell me if I'm being dumb. When robbing someone i can only see the other normal player inventory, which gives a huge advantage, police can´t seize illegal items due to this, however it might be me not knowing how to do it. Please refer to the video on the link for better explanation. https://streamable.com/zrek4z

**Comment by Brotatochips11** [comment]
I re-designed the ivnentory and merged the pockets and backpack. So basically I removed the side pockets, and the lower backpack, but added mroe top slots. If you want it just let me know on disord. brotatochips11
![image](https://github.com/iONDegen/ps-inventory/assets/55034325/f54d62ae-7fa2-4213-ae3b-878eb6e628c0)

**Comment by Brotatochips11** [comment]
![image](https://github.com/iONDegen/ps-inventory/assets/55034325/1f747b07-b060-41af-b34e-0f95194d2764)
updated image. Also works for 1440, going to optimize for 4k this weekend.

**Comment by Brave-developments** [comment]
@Brotatochips11 i added you in discord
