### ISSUE TITLE
robbing another player

### ISSUE THREAD

**Issue by chiwanay** [iONDegen/ps-inventory#19]
so... basically if you try to rob someone
1.bag is not showing up so you cant rob anything inside the bag
2.player pockets is not showing up too

so i fixed the bag by removing it (cuz i didn't like it anyway so its doesn't matter)
but the pocket, im starting to see if i can add the another player pocket to show up but i don't know if i can do it or not

if there is any way to fix it please do it.

also you can't rob the money (atleast i don't know how)

**Comment by kingblu617** [comment]
im having the same problem.. did u ever fix the player robbing?? if so how can i
